name: pyam
channels:
  - conda-forge
dependencies:
  - pandas
  - matplotlib
  - seaborn
  - six
  - pyyaml
  - xlrd
  - xlsxwriter
  - requests
  - jupyter
  - nbconvert
  - pandoc
  - geopandas
  - cartopy
  - sphinx>=1.8
  - sphinxcontrib-bibtex
  - sphinx-gallery
  - nbsphinx
  - numpydoc
  - nbformat
  - ipython
  - jupyter
  - pillow